Use model version for ssh version file name
farao-community/gridcapa-swe pull request #200
Opened 2024-03-05 16:23 UTC by schwitzguebel

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2024-03-06 10:49 UTC, WalAmeni requested changes

2024-03-06 10:49 UTC, WalAmeni commented on gridcapa-swe-runner-app/src/main/java/com/farao_community/farao/swe/runner/app/services/CgmesExportService.java
> +                sshVersionInFileName = DEFAULT_VERSION;
This block could be simpler : 
String sshVersionInFileName = cgmesSshMetadata != null ? getFormattedVersionString(cgmesSshMetadata.getSshVersion()) : DEFAULT_VERSION;

2024-03-07 08:31 UTC, danielthirion approved these changes

2024-03-07 09:04 UTC, WalAmeni approved these changes

2024-03-07 09:04 UTC, merged